#!/usr/bin/env node
/**
 * Build persona init.js — injects agent profile + last session into browser globals.
 *
 * Usage: node build-init.js personas/chris-daw
 *
 * Reads:
 *   {personaDir}/agent-profile.json → __MP_AGENT_PROFILE__
 *   {personaDir}/last-session.json  → __MP_LAST_SESSION__
 *
 * Writes:
 *   {personaDir}/init.js
 */

const fs = require("fs");
const path = require("path");

const personaDir = process.argv[2];
if (!personaDir) {
  console.error("Usage: node build-init.js <persona-dir>");
  process.exit(1);
}

const dir = path.resolve(__dirname, personaDir);

// Read agent profile
let profile = null;
const profilePath = path.join(dir, "agent-profile.json");
if (fs.existsSync(profilePath)) {
  try {
    profile = JSON.parse(fs.readFileSync(profilePath, "utf-8"));
  } catch (e) {
    console.warn(`Warning: could not parse ${profilePath}`);
  }
}

// Read last session
let lastSession = null;
const sessionPath = path.join(dir, "last-session.json");
if (fs.existsSync(sessionPath)) {
  try {
    lastSession = JSON.parse(fs.readFileSync(sessionPath, "utf-8"));
  } catch (e) {
    console.warn(`Warning: could not parse ${sessionPath}`);
  }
}

// Also check first-client subdirectory for client profiles (Ahmed lives under chris-daw/first-client/)
const firstClientProfile = path.join(dir, "first-client", "agent-profile.json");
let clientProfile = null;
if (fs.existsSync(firstClientProfile)) {
  try {
    clientProfile = JSON.parse(fs.readFileSync(firstClientProfile, "utf-8"));
  } catch {}
}

// Generate init.js
const initContent = `// Auto-generated by build-init.js — ${new Date().toISOString()}
// Persona: ${profile?.persona?.name || "Unknown"}
var __MP_AGENT_PROFILE__ = ${JSON.stringify(profile, null, 2)};
var __MP_LAST_SESSION__ = ${JSON.stringify(lastSession, null, 2)};
`;

const initPath = path.join(dir, "init.js");
fs.writeFileSync(initPath, initContent);
console.log(`Built ${initPath} (profile: ${profile?.persona?.name || "none"}, session: ${lastSession?.scenes?.length || 0} scenes)`);
